# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BoostExp100 <- function(x) {
    .Call(`_testArbitraryPrecise_BoostExp100`, x)
}

mpfrExp100 <- function(x) {
    .Call(`_testArbitraryPrecise_mpfrExp100`, x)
}

rcpp_hello_world <- function() {
    .Call(`_testArbitraryPrecise_rcpp_hello_world`)
}

